version: '2.0'
services:
  db:
    build: 
      context: ./database/
      dockerfile: db.Dockerfile
    image: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=aerlytix_vCRt65
      - POSTGRES_USER=api_user
      - POSTGRES_DB=flights
  adminer:
    image: adminer
    ports:
      - 8080:8080
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api
    ports: 
      - 2001:2001
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_NAME=flights
      - DB_USERNAME=api_user
      - DB_PASSWORD=aerlytix_vCRt65